name: snaplingua
description: Smart vocabulary learning app with AI-powered image recognition
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # GetX for state management
  get: ^4.6.6
  get_storage: ^2.1.1

  # MongoDB Realm
  realm: ^20.0.0

  # Authentication
  google_sign_in: ^6.2.1
  firebase_auth: ^5.0.0 
  # sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3

  # Camera & Image Processing
  camera: ^0.10.5+7
  image_picker: ^1.0.5
  image: ^4.1.3
  path_provider: ^2.1.1

  # ML/AI On-device
  tflite_flutter: ^0.10.4

  # Networking
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  connectivity_plus: ^5.0.2
  http: ^1.1.0

  # Storage
  shared_preferences: ^2.2.2
  sqflite: ^2.3.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI Components
  flutter_native_splash: ^2.3.8
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^2.7.0
  flutter_svg: ^2.0.9
  cupertino_icons: ^1.0.8

  # Utils
  intl: ^0.20.2
  uuid: ^4.2.2
  permission_handler: ^11.1.0
  # flutter_local_notifications: ^16.3.0
  # firebase_messaging: ^14.7.9
  url_launcher: ^6.2.2
  share_plus: ^7.2.1

  # Audio
  just_audio: ^0.9.36
  audioplayers: ^5.2.1
  flutter_tts: ^4.0.2

  # Charts & Progress
  fl_chart: ^0.66.0
  percent_indicator: ^4.2.3

  # Responsive Design
  flutter_screenutil: ^5.9.0

  # Animations
  animations: ^2.0.8
  flutter_animate: ^4.3.0

  # Cards & Swipe
  flutter_card_swiper: ^7.0.0
  flutter_slidable: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.7
  hive_generator: ^2.0.1
  realm_generator: ^20.0.0
  flutter_launcher_icons: ^0.13.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/chimcanhcut/
    - assets/images/streak/
    - assets/images/rank/
    - assets/images/nhom/
    - assets/animations/
    - assets/icons/
    - assets/ml_models/
    - assets/sounds/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/SVN-Gilroy Regular.otf
        - asset: assets/fonts/SVN-Gilroy Light.otf
          weight: 300
        - asset: assets/fonts/SVN-Gilroy Medium.otf
          weight: 500
        - asset: assets/fonts/SVN-Gilroy Bold.otf
          weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"
  remove_alpha_ios: true
  adaptive_icon_background: "#E5FFFD"
  adaptive_icon_foreground: "assets/images/logo.png"
