part of 'app_pages.dart';

abstract class Routes {
  Routes._();
  static const splash = _Paths.splash;
  static const onboarding = _Paths.onboarding;
  static const home = _Paths.home;
  static const login = _Paths.login;
  static const register = _Paths.register;
  static const survey = _Paths.survey;
  static const forgotPassword = _Paths.forgotPassword;
  static const verifyResetCode = _Paths.verifyResetCode;
  static const newPassword = _Paths.newPassword;
  static const debugData = _Paths.debugData;
  static const shop = _Paths.shop;
  static const streak = _Paths.streak;
  static const notification = _Paths.notification;
  static const profile = _Paths.profile;
  static const profileSettings = _Paths.profileSettings;
  static const profileEdit = _Paths.profileEdit;
  static const profileGoal = _Paths.profileGoal;
  static const profileChangePassword = _Paths.profileChangePassword;
  static const profileNotification = _Paths.profileNotification;
  static const profileGuide = _Paths.profileGuide;
  static const review = _Paths.review;
  static const community = _Paths.community;
  static const communityDetail = _Paths.communityDetail;
  static const communityChat = _Paths.communityChat;
  static const communityMemberProfile = _Paths.communityMemberProfile;
  static const communityCreateGroup = _Paths.communityCreateGroup;
  static const vocabularyList = _Paths.vocabularyList;
  static const vocabularyTopic = _Paths.vocabularyTopic;
  static const vocabularyFlashcard = _Paths.vocabularyFlashcard;
  static const addVocabularyCategory = _Paths.addVocabularyCategory;
  static const learningSession = _Paths.learningSession;
  static const cameraDetection = _Paths.cameraDetection;
  static const detectionResult = _Paths.detectionResult;
}

abstract class _Paths {
  _Paths._();
  static const splash = '/splash';
  static const onboarding = '/onboarding';
  static const home = '/home';
  static const login = '/login';
  static const register = '/register';
  static const survey = '/survey';
  static const forgotPassword = '/forgot-password';
  static const verifyResetCode = '/verify-reset-code';
  static const newPassword = '/new-password';
  static const debugData = '/debug-data';
  static const shop = '/shop';
  static const streak = '/streak';
  static const notification = '/notification';
  static const profile = '/profile';
  static const profileSettings = '/profile/settings';
  static const profileEdit = '/profile/edit';
  static const profileGoal = '/profile/goal';
  static const profileChangePassword = '/profile/change-password';
  static const profileNotification = '/profile/notification';
  static const profileGuide = '/profile/guide';
  static const review = '/review';
  static const community = '/community';
  static const communityDetail = '/community/detail';
  static const communityChat = '/community/chat';
  static const communityMemberProfile = '/community/member-profile';
  static const communityCreateGroup = '/community/create-group';
  static const vocabularyList = '/vocabulary-list';
  static const vocabularyTopic = '/vocabulary-topic';
  static const vocabularyFlashcard = '/vocabulary-flashcard';
  static const addVocabularyCategory = '/add-vocabulary-category';
  static const learningSession = '/learning-session';
  static const cameraDetection = '/camera-detection';
  static const detectionResult = '/detection-result';
}
